name: msp-podcast-ssl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.9

  # Core deep learning (from pytorch channel for CUDA support)
  - pytorch::pytorch>=1.13.0,<2.1.0
  - pytorch::torchaudio>=0.13.0,<2.1.0
  - pytorch::torchvision>=0.14.0,<0.16.0
  
  # CUDA toolkit (adjust version based on your cluster)
  - nvidia::cudatoolkit=11.8
  
  # Scientific computing stack
  - numpy>=1.21.0,<1.25.0
  - scipy>=1.8.0
  - scikit-learn>=1.1.0
  - pandas>=1.4.0
  
  # Audio processing essentials
  - librosa>=0.9.0
  - conda-forge::soundfile>=0.10.0
  - conda-forge::resampy>=0.3.0
  - conda-forge::ffmpeg
  
  # Development tools
  - ipython>=8.0.0
  - jupyter>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # System utilities
  - psutil>=5.8.0
  - tqdm>=4.64.0
  
  # Configuration management
  - pyyaml>=6.0
  
  # Pip packages (not available via conda)
  - pip
  - pip:
    # SpeechBrain and related
    - speechbrain>=0.5.15
    - hyperpyyaml>=1.2.0
    - omegaconf>=2.1.0
    
    # Transformers ecosystem
    - transformers>=4.20.0,<5.0.0
    - tokenizers>=0.13.0
    - huggingface-hub>=0.10.0
    
    # Logging and monitoring
    - tensorboard>=2.8.0
    - wandb>=0.13.0
    
    # Cluster utilities
    - submitit>=1.4.0
    - jsonlines>=3.0.0
    
    # Additional audio processing
    - ffmpeg-python>=0.2.0
    
    # Performance monitoring
    - memory-profiler>=0.60.0
    - py-spy>=0.3.0
    
    # Visualization (optional)
    - plotly>=5.8.0
    
    # Development tools
    - ipdb>=0.13.0