# MSP-PODCAST Emotion Classification Configuration
# Fixed version without augmentation issues

seed: 42
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Basic parameters
output_folder: !ref results/MSP_PODCAST/simple_wavlm
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# WavLM model
ssl_hub: microsoft/wavlm-large
ssl_folder: !ref <save_folder>/ssl_checkpoint

# Model configuration
batch_size: 8
emb_dim: 1024
sample_rate: 16000

# Data paths
data_folder: !PLACEHOLDER  # Set via command line
train_annotation: msp_train_10class.json
valid_annotation: msp_valid_10class.json
test_annotation: msp_test_10class.json

# Dataloader settings
train_dataloader_opts:
    batch_size: !ref <batch_size>
    shuffle: True
    num_workers: 1

valid_dataloader_opts:
    batch_size: !ref <batch_size>
    shuffle: False
    num_workers: 1

test_dataloader_opts:
    batch_size: !ref <batch_size>
    shuffle: False
    num_workers: 1

# Model definitions
ssl_model: !new:speechbrain.lobes.models.huggingface_transformers.wavlm.WavLM
    source: !ref <ssl_hub>
    output_norm: True
    freeze: True
    freeze_feature_extractor: True
    save_path: !ref <ssl_folder>

# Feature projection layer
feature_projection: !new:speechbrain.nnet.linear.Linear
    input_size: 1024  # WavLM hidden size
    n_neurons: 1024   # Keep same size

# ECAPA-TDNN
embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: 1024  # Match projection output
    channels: [1024, 1024, 1024, 1024, 3072]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    attention_channels: 128
    lin_neurons: 192

# Classifier
classifier: !new:speechbrain.lobes.models.ECAPA_TDNN.Classifier
    input_size: 192
    out_neurons: 10  # MSP-PODCAST 10 emotion classes

# Module definitions
modules:
    ssl_model: !ref <ssl_model>
    feature_projection: !ref <feature_projection>
    embedding_model: !ref <embedding_model>
    classifier: !ref <classifier>

model: !ref <embedding_model>

# Loss function
log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !name:speechbrain.nnet.losses.nll_loss

# Error calculation
error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error

# Optimizer
opt_class: !name:torch.optim.Adam
    lr: 0.001

model_opt_class: !name:torch.optim.Adam
    lr: 0.001

# Learning rate scheduler
lr_annealing_model: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: 0.001
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

# Training epochs
number_of_epochs: 20
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

# Disable sorting to avoid batching issues
sorting: random  # Change from 'ascending' to 'random'

# Checkpointer
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler_model: !ref <lr_annealing_model>
        counter: !ref <epoch_counter>

# Logger
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>