# ESP-net SER训练配置 - 修复版
batch_type: numel
batch_size: 2               # 小批量用于测试
max_epoch: 1                # 只训练1个epoch
patience: 1
seed: 42
num_workers: 1              # 减少并行度
log_interval_steps: 1
grad_clip: 5.0
accum_grad: 1

# 优化器配置
optim: adam
optim_conf:
  lr: 0.01

# 学习率调度器
scheduler: constantlr
scheduler_conf: {}

# 模型配置
model: wavlm_ecapa
model_conf:
  num_class: 10
  wavlm_model_name: "microsoft/wavlm-large"
  wavlm_freeze: true
  ecapa_channels: [256, 256]
  ecapa_kernels: [3, 3]
  ecapa_dilations: [1, 2]
  context_dim: 512
  embedding_dim: 128
  loss_type: "cross_entropy"
  label_smoothing: 0.0
  save_macro_f1: true

# 预处理器配置
preprocessor: default
preprocessor_conf:
  # 关闭SpecAugment以加速测试
  spec_augment: false

# 最佳模型选择
best_model_criterion:
  - ["valid", "acc", "max"]
  - ["valid", "loss", "min"]

# 其他配置
resume: false
keep_nbest_models: 1
use_tensorboard: false

# 分布式训练
distributed: false